"""add lan archive source registry

Revision ID: 0faff961e56e
Revises: d8a8dfc7497c
Create Date: 2026-09-10 08:05:53.314850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0faff961e56e'
down_revision: Union[str, Sequence[str], None] = 'd8a8dfc7497c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_roots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL_FAKE', 'WINDOWS_UNC', name='lan_source_type'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('allowed_subtrees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credential_reference', sa.String(length=255), nullable=True),
    sa.Column('health', sa.Enum('HEALTHY', 'UNREACHABLE', 'ACCESS_DENIED', 'PARTIAL', 'UNKNOWN', name='lan_source_health'), nullable=False),
    sa.Column('health_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_root_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='lan_scan_run_status'), nullable=False),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entries_seen', sa.Integer(), nullable=False),
    sa.Column('entries_new', sa.Integer(), nullable=False),
    sa.Column('entries_updated', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_root_id'], ['source_roots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_root_id', sa.UUID(), nullable=False),
    sa.Column('normalized_path', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_scan_id', sa.UUID(), nullable=True),
    sa.Column('discovery_status', sa.Enum('PRESENT', 'MISSING_CANDIDATE', 'CONFIRMED_MISSING', name='lan_discovery_status'), nullable=False),
    sa.Column('access_status', sa.Enum('OK', 'ACCESS_DENIED', 'NETWORK_ERROR', 'NOT_FOUND', name='lan_entry_access_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_scan_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_root_id'], ['source_roots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_root_id', 'normalized_path', name='uq_source_entry_root_path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_entries')
    op.drop_table('scan_runs')
    op.drop_table('source_roots')
    # ### end Alembic commands ###
