"""add document_relations table

Revision ID: 2e582963102d
Revises: 7ad99a85cc00
Create Date: 2026-09-06 10:39:22.304400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e582963102d'
down_revision: Union[str, Sequence[str], None] = '7ad99a85cc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('from_document_version_id', sa.UUID(), nullable=False),
    sa.Column('to_document_version_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('AMENDS', 'REPEALS', 'REPLACES', 'IMPLEMENTS', 'REFERS_TO', 'SUPERSEDED_BY', name='document_relation_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_relations')
    # ### end Alembic commands ###
    sa.Enum(name='document_relation_type').drop(op.get_bind(), checkfirst=True)
