"""add cache_hit to query_logs

Revision ID: 3ff190daf6b8
Revises: b4c20f46cb38
Create Date: 2026-09-06 15:33:53.631052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff190daf6b8'
down_revision: Union[str, Sequence[str], None] = 'b4c20f46cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows logged before this column
    # existed (a NOT NULL add with no default fails against a non-empty
    # table); dropped afterwards so future ORM inserts always supply it
    # explicitly via QueryLog's Python-side default.
    op.add_column(
        'query_logs',
        sa.Column('cache_hit', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.alter_column('query_logs', 'cache_hit', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'cache_hit')
    # ### end Alembic commands ###
