"""add document_regions and document_nodes for M3 generic parsing

Revision ID: 4d9792a02a8e
Revises: 46149f863b67
Create Date: 2026-09-03 09:38:15.230889

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d9792a02a8e'
down_revision: str | Sequence[str] | None = '46149f863b67'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('region_type', sa.Enum('COVER', 'TABLE_OF_CONTENTS', 'LEGAL_PREAMBLE', 'LEGAL_BODY', 'LEGAL_DECISION', 'TECHNICAL_GUIDELINE', 'PROCEDURAL_GUIDELINE', 'NUMBERED_MANUAL', 'SOP', 'APPENDIX', 'TABLE_REGION', 'DIAGRAM_REGION', 'ORGANIZATION_CHART', 'FLOWCHART', 'EMBEDDED_TEMPLATE', 'ACADEMIC_TEMPLATE', 'FREEFORM_SECTION', 'UNKNOWN', name='structural_region_type'), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('previous_id', sa.UUID(), nullable=True),
    sa.Column('next_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.Enum('DOCUMENT', 'REGION', 'TITLE', 'SUBTITLE', 'CHAPTER', 'PART', 'SECTION', 'SUBSECTION', 'NUMBERED_SECTION', 'NUMBERED_ITEM', 'LETTER_ITEM', 'ROMAN_ITEM', 'NESTED_ITEM', 'ARTICLE', 'CLAUSE', 'DECISION_ITEM', 'PARAGRAPH', 'LIST', 'LIST_ITEM', 'TABLE', 'TABLE_ROW', 'TABLE_CELL', 'APPENDIX', 'FIGURE', 'DIAGRAM', 'FLOWCHART', 'ORGANIZATION_CHART', 'FOOTNOTE', 'SIGNATURE_BLOCK', 'UNKNOWN_BLOCK', name='document_node_type'), nullable=False),
    sa.Column('semantic_role', sa.Enum('GENERAL', 'PURPOSE', 'OBJECTIVE', 'SCOPE', 'LEGAL_BASIS', 'DEFINITION', 'POSITION', 'PRINCIPLE', 'PLANNING', 'PREPARATION', 'EXECUTION', 'TERMINATION', 'PROCEDURE', 'REQUIREMENT', 'RESPONSIBILITY', 'AUTHORITY', 'DUTY', 'PROHIBITION', 'COMMAND', 'CONTROL', 'DECISION', 'VALIDITY', 'ORGANIZATION_STRUCTURE', 'PROCESS_FLOW', 'CONCLUSION', 'RECOMMENDATION', 'UNKNOWN', name='semantic_role'), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('number_raw', sa.String(length=64), nullable=True),
    sa.Column('number_normalized', sa.String(length=64), nullable=True),
    sa.Column('numbering_style', sa.Enum('DECIMAL_DOT', 'DECIMAL_PAREN_CLOSE', 'DECIMAL_PAREN_FULL', 'LETTER_DOT', 'LETTER_PAREN_CLOSE', 'LETTER_PAREN_FULL', 'ROMAN_UPPER_DOT', 'ROMAN_LOWER_DOT', 'LETTER_UPPER_DOT', 'ORDINAL_WORD', 'UNKNOWN', name='numbering_style'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structural_path_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structural_depth', sa.Integer(), nullable=False),
    sa.Column('visual_source_type', sa.String(length=64), nullable=True),
    sa.Column('chapter_number', sa.String(length=64), nullable=True),
    sa.Column('article_number', sa.String(length=64), nullable=True),
    sa.Column('clause_number', sa.String(length=64), nullable=True),
    sa.Column('letter_number', sa.String(length=64), nullable=True),
    sa.Column('appendix_number', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['next_id'], ['document_nodes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ),
    sa.ForeignKeyConstraint(['previous_id'], ['document_nodes.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['document_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_nodes')
    op.drop_table('document_regions')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the enum types it created (same gap as M1/M2's
    # baseline migrations) — do it by hand so a downgrade->upgrade cycle works.
    sa.Enum(name='numbering_style').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='semantic_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_node_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='structural_region_type').drop(op.get_bind(), checkfirst=True)
