"""add lan archive promotion records

Revision ID: a7057580f523
Revises: 0faff961e56e
Create Date: 2026-09-10 13:10:05.696852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7057580f523'
down_revision: Union[str, Sequence[str], None] = '0faff961e56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source_entry_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'STABILITY_WAIT', 'STAGING', 'DUPLICATE_LINKED', 'COMPLETED', 'FAILED', 'PAUSED_CAPACITY', name='lan_promotion_status'), nullable=False),
    sa.Column('lease_owner', sa.UUID(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_entry_id'], ['source_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_entry_id', name='uq_promotion_record_source_entry')
    )
    op.add_column('document_versions', sa.Column('source_entry_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'document_versions', 'source_entries', ['source_entry_id'], ['id'])
    op.add_column('source_roots', sa.Column('knowledge_space_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'source_roots', 'knowledge_spaces', ['knowledge_space_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_roots', type_='foreignkey')
    op.drop_column('source_roots', 'knowledge_space_id')
    op.drop_constraint(None, 'document_versions', type_='foreignkey')
    op.drop_column('document_versions', 'source_entry_id')
    op.drop_table('promotion_records')
    # ### end Alembic commands ###
