"""add structural_path_text and document_structure_profiles

Revision ID: edcf000c1933
Revises: 4d9792a02a8e
Create Date: 2026-09-03 11:46:45.130287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcf000c1933'
down_revision: Union[str, Sequence[str], None] = '4d9792a02a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_structure_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('contains_articles', sa.Boolean(), nullable=False),
    sa.Column('contains_numbered_sections', sa.Boolean(), nullable=False),
    sa.Column('contains_chapters', sa.Boolean(), nullable=False),
    sa.Column('contains_decision_preamble', sa.Boolean(), nullable=False),
    sa.Column('contains_appendices', sa.Boolean(), nullable=False),
    sa.Column('contains_tables', sa.Boolean(), nullable=False),
    sa.Column('contains_diagrams', sa.Boolean(), nullable=False),
    sa.Column('contains_embedded_document', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id')
    )
    op.add_column('document_nodes', sa.Column('structural_path_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_nodes', 'structural_path_text')
    op.drop_table('document_structure_profiles')
    # ### end Alembic commands ###
